#!/usr/bin/env bash
# =============================================================================
# start.sh — Model selector for llama.cpp Docker wrapper
#
# Usage:
#   ./start.sh              # Interactive menu
#   ./start.sh qwen3-coder  # Direct launch by section ID
#   ./start.sh --list       # List available models
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF="$SCRIPT_DIR/models.conf"
MODELS_DIR="$SCRIPT_DIR/models"
ENV_FILE="$SCRIPT_DIR/.env"

# --- INI parser -----------------------------------------------------------
# Reads models.conf into parallel arrays. No eval, no external tools.

declare -a SECTION_IDS=()
declare -a SECTION_NAMES=()
declare -A CONFIG=()  # CONFIG[section.KEY]=value

parse_conf() {
    local section=""
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Strip leading/trailing whitespace
        line="${line#"${line%%[![:space:]]*}"}"
        line="${line%"${line##*[![:space:]]}"}"

        # Skip empty lines and comments
        [[ -z "$line" || "$line" == \#* ]] && continue

        # Section header
        if [[ "$line" =~ ^\[([a-zA-Z0-9_-]+)\]$ ]]; then
            section="${BASH_REMATCH[1]}"
            SECTION_IDS+=("$section")
            continue
        fi

        # Key=Value
        if [[ -n "$section" && "$line" == *=* ]]; then
            local key="${line%%=*}"
            local value="${line#*=}"
            CONFIG["${section}.${key}"]="$value"
            if [[ "$key" == "NAME" ]]; then
                SECTION_NAMES+=("$value")
            fi
        fi
    done < "$CONF"
}

# --- Helpers ---------------------------------------------------------------

get() { echo "${CONFIG["${1}.${2}"]:-}"; }

die() { echo "Error: $*" >&2; exit 1; }

ctx_label() {
    local ctx="$1"
    if (( ctx >= 262144 )); then echo "256K ctx"
    elif (( ctx >= 131072 )); then echo "128K ctx"
    elif (( ctx >= 65536 )); then echo "64K ctx"
    else echo "${ctx} ctx"
    fi
}

list_models() {
    echo "Available models:"
    echo ""
    for i in "${!SECTION_IDS[@]}"; do
        local id="${SECTION_IDS[$i]}"
        local name="${SECTION_NAMES[$i]}"
        local ctx; ctx=$(get "$id" CTX_SIZE)
        printf "  %-20s  %s" "$id" "$name"
        [[ -n "$ctx" ]] && printf "  (%s)" "$(ctx_label "$ctx")"
        printf "\n"
    done
}

# --- Prerequisite checks ---------------------------------------------------

check_docker() {
    if ! command -v docker &>/dev/null; then
        die "docker not found. Install Docker first."
    fi
    if ! docker info &>/dev/null 2>&1; then
        die "Docker daemon is not running."
    fi
}

check_existing_container() {
    local state
    state=$(docker inspect --format='{{.State.Status}}' llama-server 2>/dev/null || true)
    if [[ "$state" == "running" ]]; then
        echo "Container 'llama-server' is already running."
        read -rp "Stop it and continue? [y/N] " answer
        if [[ "${answer,,}" == "y" ]]; then
            docker compose -f "$SCRIPT_DIR/docker-compose.yml" down
        else
            echo "Aborted."
            exit 0
        fi
    fi
}

# --- .env generation -------------------------------------------------------

generate_env() {
    local id="$1"
    local model; model=$(get "$id" MODEL)
    local ctx; ctx=$(get "$id" CTX_SIZE)
    local ngl; ngl=$(get "$id" N_GPU_LAYERS)
    local fit; fit=$(get "$id" FIT)
    local extra; extra=$(get "$id" EXTRA_ARGS)

    {
        echo "# Generated by start.sh — $(get "$id" NAME)"
        echo "# Section: [$id] from models.conf"
        echo ""
        [[ -n "$model" ]] && echo "MODEL=$model"
        [[ -n "$ctx" ]]   && echo "CTX_SIZE=$ctx"
        [[ -n "$ngl" ]]   && echo "N_GPU_LAYERS=$ngl"
        [[ -n "$fit" ]]   && echo "FIT=$fit"
        [[ -n "$extra" ]] && echo "EXTRA_ARGS=$extra"
    } > "$ENV_FILE"
}

# --- Model file check ------------------------------------------------------

check_model_file() {
    local id="$1"
    local model; model=$(get "$id" MODEL)
    local full_path="$MODELS_DIR/$model"
    if [[ ! -f "$full_path" ]]; then
        die "Model file not found: $full_path
Download it first, then try again."
    fi
}

# --- Menu -------------------------------------------------------------------

show_menu() {
    echo ""
    echo "llama.cpp Model Selector"
    echo "========================"
    echo ""

    for i in "${!SECTION_IDS[@]}"; do
        local id="${SECTION_IDS[$i]}"
        local name="${SECTION_NAMES[$i]}"
        local ctx; ctx=$(get "$id" CTX_SIZE)
        local label=""
        [[ -n "$ctx" ]] && label=$(ctx_label "$ctx")
        printf "  %d) %-48s %s\n" "$((i + 1))" "$name" "$label"
    done

    echo ""
    echo "  q) Quit"
    echo ""

    local count=${#SECTION_IDS[@]}
    while true; do
        read -rp "Select model [1-${count}]: " choice
        if [[ "$choice" == "q" || "$choice" == "Q" ]]; then
            echo "Aborted."
            exit 0
        fi
        if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= count )); then
            echo "${SECTION_IDS[$((choice - 1))]}"
            return
        fi
        echo "Invalid choice. Enter 1-${count} or q to quit."
    done
}

# --- Main -------------------------------------------------------------------

[[ ! -f "$CONF" ]] && die "Config file not found: $CONF"

parse_conf

if [[ ${#SECTION_IDS[@]} -eq 0 ]]; then
    die "No models defined in $CONF"
fi

# Handle arguments
selected=""

if [[ $# -ge 1 ]]; then
    case "$1" in
        --list|-l)
            list_models
            exit 0
            ;;
        --help|-h)
            echo "Usage: $0 [model-id | --list | --help]"
            echo ""
            list_models
            exit 0
            ;;
        *)
            # Direct model ID
            found=false
            for id in "${SECTION_IDS[@]}"; do
                if [[ "$id" == "$1" ]]; then
                    selected="$1"
                    found=true
                    break
                fi
            done
            if [[ "$found" == false ]]; then
                echo "Error: Unknown model '$1'" >&2
                echo ""
                list_models >&2
                exit 1
            fi
            ;;
    esac
fi

check_docker

# Interactive menu if no model specified
if [[ -z "$selected" ]]; then
    selected=$(show_menu)
fi

echo ""
echo "Selected: $(get "$selected" NAME)"

check_model_file "$selected"
check_existing_container
generate_env "$selected"

echo "Generated .env for [$selected]"
echo "Starting docker compose..."
echo ""

exec docker compose -f "$SCRIPT_DIR/docker-compose.yml" up
